### PR TITLE
Improve SourceResampler

### PR DESCRIPTION
**Pull request by tischi**
Hi @NicoKiaru,

Here's making the resampled source name configurable. 

Happy?

I was not sure how to do it best in the Command...

### CODE REVIEW

**Comment by tischi** [comment]
@NicoKiaru I added the `voxelDimensions`. OK?

**Comment by NicoKiaru** [comment]
Looks great!

**Comment by tischi** [comment]
@NicoKiaru
OK, please merge if you are happy.

**Review by NicoKiaru — APPROVED** [review]
All looks good to me. Thanks @tischi

**Pull request merged**
