### PR TITLE
Betterresampler

### PR DESCRIPTION
**Pull request by NicoKiaru**
This PR improves the resampled source mechanism.

[Resampled sources](https://github.com/bigdataviewer/bigdataviewer-playground/blob/9de195abbc551759df648a1d9479965a537f1cad/src/main/java/bdv/util/ResampledSource.java) allow, for instance, to extract a part of a large dataset by specifying a region and a sampling size (voxel size).  The region and the voxel size can actually be defined by another SourceAndConverter.

This mechanism already exists. What this PR does is that it's improving the resampling by adapting the required voxel size to the level of resolution required by the resampled source. See 

MontageMipMapInterpolate

The orange  image is badly resampled (mipmap chosen for the resampling not correct) while the green one uses the correct level.

This PR adds a few methods for [estimating the voxel size of a source](https://github.com/bigdataviewer/bigdataviewer-playground/blob/546c052dee4a495f6e5ff7abb7ccb4cc0f599707/src/main/java/sc/fiji/bdvpg/sourceandconverter/SourceAndConverterUtils.java#L941), for finding the [best matching resolution level to a certain voxel size](https://github.com/bigdataviewer/bigdataviewer-playground/blob/546c052dee4a495f6e5ff7abb7ccb4cc0f599707/src/main/java/sc/fiji/bdvpg/sourceandconverter/SourceAndConverterUtils.java#L836), and modifies the resampling demo to show this effect.

### CODE REVIEW

**Comment by NicoKiaru** [comment]
Hi @tischi, let me know if that looks ok for you.

**Comment by tischi** [comment]
Hi Nico,

I guess you don't need a full review here, right? Just best practice to work with PRs, is it?

I have a minor request, in below two methods...
- https://github.com/bigdataviewer/bigdataviewer-playground/blob/546c052dee4a495f6e5ff7abb7ccb4cc0f599707/src/main/java/sc/fiji/bdvpg/sourceandconverter/SourceAndConverterUtils.java#L941
- https://github.com/bigdataviewer/bigdataviewer-playground/blob/546c052dee4a495f6e5ff7abb7ccb4cc0f599707/src/main/java/sc/fiji/bdvpg/sourceandconverter/SourceAndConverterUtils.java#L836

...would it be OK for you to rename `at3d` to `sourceTransform`? I think this would make it easier to understand what is going on (if one only has a quick glance at the code).

Let me know if you want me to fully test it (although honestly I don't have much time right now....)

**Comment by NicoKiaru** [comment]
Thanks. No of course I don't need a full review. But just like that we are informed of what we do. And general comments are fine.

I'll change the names.

**Comment by tischi** [comment]
ok. you can then merge yourself :)

**Comment by NicoKiaru** [comment]
Ok done, I merge now

**Pull request merged**
